name: hipokrates
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.0
  another_flushbar: ^1.10.29
  flutter_switch: ^0.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/homeCards/
    - assets/images/ProfileCards/
    - assets/images/flags/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

